### ISSUE TITLE
Error after deployment

### ISSUE THREAD

**Issue by muralikizhuvettil01** [OfficeDev/microsoft-teams-celebrations-app#22]
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable

**Comment by muralikizhuvettil01** [comment]
![teams celebration error](https://user-images.githubusercontent.com/102357273/193288756-4399326f-8b2b-4b65-ac7a-a2f14ffd3068.png)

**Comment by aidab98** [comment]
How was this solved? I have the same issue.
