### ISSUE TITLE
Not able to upload the App to Teams

### ISSUE THREAD

**Issue by rajivsr23** [OfficeDev/microsoft-teams-celebrations-app#7]
On the Teams Desktop Client, I follow these steps-
1. Apps
2. Upload a custom App
3. Upload the Zip File

Error Message
`Error while extracting package: Please ensure there are no folders in your app package and that your app package contains only the manifest.json and the two required icon files at its root level. For an easier experience creating your app package, install <a href="https://teams.microsoft.com/l/app/0c5cfdbb-596f-4d39-b557-5d9516c94107" target="_blank">App Studio</a> from the Teams Store.`

The Zip Folder contains-
1. manifest.json
2. outline.png
3. color.png

**Comment by rajivsr23** [comment]
[Manifest.zip](https://github.com/OfficeDev/microsoft-teams-celebrations-app/files/4713547/Manifest.zip)

Uploaded the Manifest Folder

**Comment by rashmi-dixit** [comment]
The Zip folder uploaded by you contains a folder Manifest inside which 3 files (manifest.json, outline.png,color.png) are placed. The 3 files should be at top level of the ZIP package, with no nested folders. To make a zip package select all files and send to zipped folder.

**Comment by rajivsr23** [comment]
Thank you! This worked.
